language: c

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.18.7
    - CRYSTAL_VERSION=0.19.4
    - CRYSTAL_VERSION=0.20.1

install:
  - curl -L https://raw.github.com/pine/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version
  - shards --version

before_script:
  - shards

script:
  - crystal spec -v
