language: c

env:
  global:
    - PATH=$HOME/.crenv/bin:$PATH
  matrix:
    - CRYSTAL_VERSION=0.18.7
    - CRYSTAL_VERSION=0.19.4
    - CRYSTAL_VERSION=0.20.1

install:
  - curl -L https://raw.github.com/pine/crenv/master/install.sh | bash
  - eval "$(crenv init -)"
  - crenv install $CRYSTAL_VERSION
  - crenv global $CRYSTAL_VERSION
  - crystal --version
  - shards --version

before_script:
  - shards

script:
  - crystal spec -v

notifications:
  slack:
    - secure: "UoOJTI44RDTI05BahA0zRQAR9ZX538+nhPWb+4q7VE8zymZXFTytFmmLsY9fBTSXnDRKXgSYezGNpkHvsONFNRiIjjYEWx1diuM8Bpet68PJmNM9TPf7NN0NLZ5uvm151O2k4U7Ra3MNdKLrFHsw3q3ZpHuQlpQD68TFFoqUHEz1f/eTpwx+B5+Krxs+fgc45r5SATPrBDY8rnZ7GiPHvoI3yAvnq+hwuEjqdT09p2q18/dg/E6MkUhrKil20Ap/YbkrlYbAr107ieCrtC0MpREKdcWt0sZWNoncUAjNczIauXToQLZHxuQZ058g5hKa1jhciH+kJZsVU+kJK0hIJzrVAF7VESNKoqmrSCE7wafFzJjvjUJ0Q/OIoWOKLRlkxyGg8oLAHhqCWWqNFJE7uewKl8R0Hmg7pTlr34+/Cy1IxXsmiWUmta1CDjg2qpZTcmiMYRBmFiacMcorNB5TGEdQf6G97WPQV6ovnjm4svk/6sJxE7toXsu5NOKdN0Bh5O4yBWl6+lAABF3O4ZFyrCghXJpY+BjZEkfuT9Zhd5W3p9NtLOBFT+gZ+eTjdNzHForBj2FGQWmsBnTlYp2N9pw7BtEQX+sThGEbuhw6/MrNJdIHY2Wizayz670fibHmsXDCFCQLJwvKud5Vf0+jaMODJuNjAtlkyfAvUothesk="
